exclude: [Gemfile, Gemfile.lock, Rakefile, README.md, vendor]
title: Saturday Pain
description: >- # this means to ignore newlines until next config
  How to run a simple park exercise group.
sass:
  style: compressed
  sass_dir: _assets
