name: Test build

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  test:
    name: Test build the site
    runs-on: ubuntu-24.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake
